import { apiClient } from '@/lib/axios';
import type { ApiSuccessEnvelope } from '@/types/api.types';

import type { PlaceOrderPayload, PlaceOrderResponse } from '@/features/checkout/types/checkout.types';

/**
 * Axios calls for the checkout feature (Section 11.4 `POST /api/v1/orders`).
 * The idempotency key (Section 11.7 business rules) is generated by the
 * caller once per checkout attempt and reused across retries so a network
 * retry never creates a duplicate order.
 */
export const checkoutApi = {
  placeOrder: async (payload: PlaceOrderPayload): Promise<PlaceOrderResponse> => {
    const { data } = await apiClient.post<ApiSuccessEnvelope<PlaceOrderResponse>>(
      '/orders',
      payload,
      { headers: { 'Idempotency-Key': payload.idempotencyKey } },
    );
    return data.data;
  },
};
